services:
  - type: web
    name: mr-yunks-moderation-bot
    env: python
    plan: free
    buildCommand: "pip install -r moderation_bot/requirements.txt"
    startCommand: "python -m moderation_bot.main"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: mr-yunks-moderation-bot
          property: url